
project_id = "ebviljrakjsjymsqejqu"

[functions.seed-events]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
# Add these properties for additional security and proper redirect handling
authorization_endpoint = "https://accounts.google.com/o/oauth2/auth"
token_endpoint = "https://oauth2.googleapis.com/token"
jwks_uri = "https://www.googleapis.com/oauth2/v3/certs"
user_info_endpoint = "https://www.googleapis.com/oauth2/v3/userinfo"
