
project_id = "ebviljrakjsjymsqejqu"

[functions.seed-events]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
