
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebviljrakjsjymsqejqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidmlsanJha2pzanltc3FlanF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjk0MjIsImV4cCI6MjA2MDQwNTQyMn0.DyzoBp9PvHioQvyyr1vW3DsecMgUTjvugavR0lu-I38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web/2.49.4',
    },
  },
});

// Helper functions for common operations
export const syncUsersToProfiles = async () => {
  console.log("Starting user sync process...");
  try {
    // First sync users to profiles (older method)
    const { error: profileError } = await supabase.rpc('sync_users_to_profiles');
    if (profileError) {
      console.error("Error in sync_users_to_profiles RPC:", profileError);
    }
    
    // Then sync auth.users to public.users (new method)
    const { error: usersError } = await supabase.rpc('sync_all_users');
    if (usersError) {
      console.error("Error in sync_all_users RPC:", usersError);
      throw usersError;
    }
    
    console.log("User sync completed successfully");
    return { success: true };
  } catch (err) {
    console.error("Exception in syncUsersToProfiles:", err);
    throw err;
  }
};
